### ISSUE TITLE
Release httptest 4.0.0

### ISSUE THREAD

**Issue by nealrichardson** [nealrichardson/httptest#53]
cc @jonkeane @maelle 

There are a few new features, plus better support for testthat 3rd edition, so a release would be good. 

Checklist:

- [x] Fix interactive test running (#51)
- [x] Add with_mock_dir and update docs (#48, #40) 
- [x] Use testthat::test_path or similar where appropriate in .mockPaths() (#52)
- [x] Something similar for vignette running? (#55, #31)
- [x] Something similar for with_mock_dir (#57)
- [x] Add @maelle to contributors in DESCRIPTION (assuming you 👍 )
- [x] Improve FAQ (#54)
- [x] revdep checks 
- [x] Update NEWS
- [x] Confirm whether Windows UTF-8 issue fixed (@max-alletsee, other point on #31)  Update: it apparently isn't fixed, so we'll have to revisit later.
- [ ] Docs on testing error behavior (#43)
- [x] Look into removing deprecated function aliases (buildMockURL et al.), depending on revdeps
  - [x] Release [httpcache](https://github.com/nealrichardson/httpcache/releases/tag/1.2.0)
  - [x] Release [pivotaltrackR](https://github.com/nealrichardson/pivotaltrackR/releases/tag/0.2.0)
  - [x] AlphaVantageClient (https://github.com/athompson1991/AlphaVantageClient/pull/1)
  - [x] crunch, crunchy, crplyr (https://github.com/Crunch-io/rcrunch/pull/528)
  - [ ] edgarWebR (https://github.com/mwaldstein/edgarWebR/pull/17)
  - [x] rGoodData (https://github.com/byapparov/rGoodData/pull/10)

**Comment by maelle** [comment]
Thanks for adding me as contributor, I appreciate it :pray:

So #49 is out-of-scope for this release?

Reg #43 I think it'd just be a matter of copy-pasting from other sources so could be done before release? (your blog post, https://github.com/ropensci-books/http-testing/pull/47/files#diff-d7ac0bbc0eb16d66139463bc6fd3b5fa861fd15ef8903ef4eb9276072d29610f) Well, if deemed useful, of course. :-)

**Comment by nealrichardson** [comment]
> So #49 is out-of-scope for this release?

I think it would be nice to have, but I don't know how trivial it is going to be, and I don't have a ton of time to work on this going forward (was taking advantage of a few days off of work to catch up here). I'll give it some thought and see if it comes together, but I don't think it needs to block releasing the rest of the improvements

> Reg #43 I think it'd just be a matter of copy-pasting from other sources so could be done before release?

Added to the checklist, thanks.

**Comment by nealrichardson** [comment]
Submitted to CRAN. I did not get to #43 but we can pick it up after the release.
